<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-ABLBB1N" failures="1" tests="7" name="Test" time="163.873" errors="0" timestamp="2024-12-31T18:24:24 IST">
  <testcase classname="testCases.TC001_AccountRegistrationTest" name="verify_account_registration" time="11.385"/>
  <testcase classname="testCases.TC002_LoginTest" name="verify_login" time="8.891"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="11.817"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="34.231"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="36.903"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="5.93">
    <failure type="java.lang.AssertionError" message="Login succeeded with invalid credentials.">
      <![CDATA[java.lang.AssertionError: Login succeeded with invalid credentials.
at testCases.TC003_LoginDDT.verify_loginDDT(TC003_LoginDDT.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="33.633"/>
</testsuite> <!-- Test -->
