<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-ABLBB1N" failures="1" tests="5" name="Test" time="125.815" errors="0" timestamp="2024-12-31T17:10:44 IST">
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="7.712"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="32.726"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="33.709"/>
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="4.932">
    <failure type="java.lang.AssertionError" message="Login succeeded with invalid credentials.">
      <![CDATA[java.lang.AssertionError: Login succeeded with invalid credentials.
at testCases.TC003_LoginDDT.verify_loginDDT(TC003_LoginDDT.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
  <testcase classname="testCases.TC003_LoginDDT" name="verify_loginDDT" time="32.411"/>
</testsuite> <!-- Test -->
